name = "ESDLColombia"
uuid = "bce5d1ce-5a90-11e9-1aa5-45e42cd759bf"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de>"]
version = "0.1.0"

[deps]
ESDL = "359177bc-a543-11e8-11b7-bb015dba3358"

[compat]
julia = "1.0"
